api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/<pk>/', views.ProductDetailView.as_view(), name='product_detail'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.CartAddView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('', views.CartDetailView.as_view(), name='cart_detail'),

]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
    
]

ecom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('api/', include('api.urls', namespace='api')),


    path('', include('products.urls', namespace='product') ),
    # User management
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='order_create'),
    path('order-successful/', views.OrderCreatedView.as_view(), name='order_created'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    



]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICE = [(i, str(i)) for i in range(1,21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICE, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render
from django.urls import reverse
from .forms import CartAddProductForm
from .cart import Cart
from products.models import Product
from django.views.decorators.http import require_POST
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView, View

from coupons.forms import CouponApplyForm
from products.recommender import Recommender

# Create your views here.


class CartAddView(View):
    
    
    def post(self, request, product_id, *args, **kwargs):

        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
                     quantity=cd['quantity'],
                     override=cd['override'])
        return redirect('cart:cart_detail')
    
class CartRemoveView(View):
    def post(self, request, product_id, *args, **kwargs):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        # form = CartAddProductForm(request.POST)
        # if form.is_valid():
        #     cd = form.cleaned_data
            
        cart.remove(product)
        return redirect('cart:cart_detail')
    
class CartDetailView(View):
    
    context_object_name = 'cart'
    template_name = 'cart/cart_detail.html'
    def get(self, request, *args, **kwargs):
        coupon_apply_form = CouponApplyForm()
        cart = Cart(request)
        for item in cart:
            item['update_quantity_form']= CartAddProductForm(initial={
                'quantity': item['quantity'],
                'override': True,
            })
        r = Recommender()
        cart_products = [item['product'] for item in cart]
        if (cart_products):
            recommended_products = r.suggest_products_for(cart_products, max_results=4)
        else:
            recommended_products = []


        return render(request, self.template_name, context={'cart':cart,
                                                            'coupon_apply_form': coupon_apply_form,
                                                            'recommended_products':recommended_products})
    
    

    # def get_queryset(self, request):
    #     cart = Cart(request)
    #     return cart
        
            

cart/templates/cart/cart_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cart{% endblock title %}

{% block content %}
  <h1>Your shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}
                {% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      {% if cart.coupon %}
        <tr class="subtotal">
          <td>Subtotal</td>
          <td colspan="4"></td>
          <td class="num">${{ cart.get_total_price|floatformat:2 }}</td>
        </tr>
        <tr>
          <td>
            "{{ cart.coupon.code }}" coupon
            ({{ cart.coupon.discount }}% off)
          </td>
          <td colspan="4"></td>
          <td class="num neg">
            - ${{ cart.get_discount|floatformat:2 }}
          </td>
        </tr>
      {% endif %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">
          ${{ cart.get_total_price_after_discount|floatformat:2 }}
        </td>
      </tr>
    </tbody>
  </table>
  
 

  <p>Apply a coupon:</p>
  <form action="{% url 'coupons:apply' %}" method="post">
    {{ coupon_apply_form }}
    <input type="submit" value="Apply">
    {% csrf_token %}
  </form>
  <p class="text-right">
    <a href="{% url 'product:product_list' %}" class="button
    light">Continue shopping</a>
    <a href="{% url 'orders:order_create' %}" class="button">Checkout</a>
  </p>

  {% if recommended_products %}
  <div class="recommendations cart">
    <h3>People who bought this also bought</h3>
    {% for p in recommended_products %}
      <div class="item">
        <a href="{{ p.get_absolute_url }}">
          
        </a>
        <p><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></p>
      </div>
    {% endfor %}
  </div>
{% endif %}
{% endblock %}