api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/<pk>/', views.ProductDetailView.as_view(), name='product_detail'),

]

ecom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('api/', include('api.urls', namespace='api')),


    path('', include('products.urls', namespace='product') ),
    # User management
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    
]

payment/urls.py
from django.urls import path
from . import views
from . import webhooks

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('success/', views.payment_success, name='completed'),
    path('cancel/', views.payment_cancel, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),

]

payment/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
import stripe
from django.conf import settings
from orders.models import Order
from decimal import Decimal


# Create your views here.


stripe.api_key = settings.STRIPE_SECRET_KEY
stripe.api_version = settings.STRIPE_API_VERSION



def payment_process(request):
    order_id = request.session.get('order_id', None)
    order = get_object_or_404(Order, id=order_id)
    
    if request.method == 'POST':
        success_url = request.build_absolute_uri(reverse('payment:completed'))
        cancel_url = request.build_absolute_uri(reverse('payment:canceled'))
        # stripe checkout session data
        session_data = {
            'mode': 'payment',
            'client_reference_id': order.id,
            'success_url': success_url,
            'cancel_url': cancel_url,
            'line_items': [], 
            

        }
        # add order items to the stripe checkout sesion
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data': {
                    'unit_amount': int(item.price * Decimal('100')),
                    'currency': 'aed',
                    'product_data':{
                        'name': item.product.title,
                    },
                },
                'quantity': item.quantity,
            })

        # stripe coupon
        if order.coupon:
            stripe_coupon = stripe.Coupon.create(
                name=order.coupon.code,
                percent_off=order.discount,
                duration='once',
            )
            session_data['discounts'] = [{ 'coupon': stripe_coupon.id}]
        # create stripe checkout session
        session = stripe.checkout.Session.create(**session_data)
        # redirect to stripe payment form
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html', locals())

def payment_success(request):
    return render(request, 'payment/completed.html')


def payment_cancel(request):
    return render(request, 'payment/canceled.html')

payment/templates/payment/canceled.html
{% extends 'base.html' %}

{% block title %}Pyament canceled{% endblock title %}

{% block content %}
    <h1> your payment is <strong>canceled</strong></h1>

{% endblock content %}

payment/templates/payment/completed.html
{% extends 'base.html' %}

{% block title %}Pyament canceled{% endblock title %}

{% block content %}
    <h1> your payment is <strong>completed</strong></h1>

{% endblock content %}

payment/templates/payment/process.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Pyament canceled{% endblock title %}

{% block content %}

<h1>Order summary</h1>
<table class="cart">
<thead>
<tr>
<th>Image</th>
<th>Product</th>
<th>Price</th>
<th>Quantity</th>
<th>Total</th>
</tr>
</thead>
<tbody>
    {% for item in order.items.all %}
    <tr class="row{% cycle '1' '2' %}">
    <td>
    <img src="{% if item.product.image %}{{ item.product.image.url }}
    {% else %}{% static 'img/no_image.png' %}{% endif %}">
    </td>
    <td>{{ item.product.title }}</td>
    <td class="num">AED {{ item.price }}</td>
    <td class="num">{{ item.quantity }}</td>
    <td class="num">AED {{ item.get_cost }}</td>
    </tr>
    {% endfor %}
    <tr class="total">
    <td colspan="4">Total</td>
    <td class="num">AED {{ order.get_total_cost }}</td>
    </tr>

    {% if order.coupon %}
 <tr class="subtotal">
 <td>Subtotal</td>
 <td colspan="3"></td>
 <td class="num">
 ${{ order.get_total_cost_before_discount|floatformat:2 }}
 </td>
 </tr>
 <tr>
 <td>
 "{{ order.coupon.code }}" coupon
 ({{ order.discount }}% off)
 </td>
 <td colspan="3"></td>
 <td class="num neg">
 - ${{ order.get_discount|floatformat:2 }}
 </td>
 </tr>
{% endif %}

    </tbody>
    </table>

    <form action="{% url 'payment:process' %}" method="post">
        <input type="submit" value="Pay now">
        {% csrf_token %}
    </form>

{% endblock content %}