api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/<pk>/', views.ProductDetailView.as_view(), name='product_detail'),

]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.CartAddView.as_view(), name='cart_add'),
    path('remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('', views.CartDetailView.as_view(), name='cart_detail'),

]

ecom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('api/', include('api.urls', namespace='api')),


    path('', include('products.urls', namespace='product') ),
    # User management
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    
]

products/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='home'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('categories/', views.CategoryListView.as_view(), name='category_list'),
 # path('<int:product_id>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('<str:slug>/',views.ProductDetailView.as_view(), name='product_detail'),
]

products/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    root = models.ForeignKey('self', default=None, null=True,
                              blank=True, on_delete=models.SET_NULL, related_name='subcategories')
    
    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
            ]
        verbose_name, verbose_name_plural = 'category', 'categories'

    def __str__(self) -> str:
        return self.name
    
class Brand(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    logo = models.FileField(upload_to='product/brands/', default='unknown.jpg', blank=True)
    website = models.CharField(max_length=200, default=None, null=True,blank=True )

    class Meta:
        verbose_name, verbose_name_plural = 'brand', 'brands'
        ordering = ['name']
        indexes =[
            models.Index(fields=['name']),

        ]
    def __str__(self) -> str:
        return self.name
    
class Discount(models.Model):
    class Meta:
        verbose_name, verbose_name_plural = 'discount', 'discounts'

    amount = models.PositiveBigIntegerField(default=0, null=True, blank=True)
    start_date = models.DateTimeField(default=timezone.now, null=True, blank=True)
    end_date = models.DateTimeField(default=None, null=True, blank=True)

    def calculate_price(self, price: int) -> int:
        decrease, present = 0, timezone.now()
        if self.start_date <= present :
            if self.end_date is None or present <= self.end_date:
                percentage = self.amount / 100
                decrease_amount = price * percentage
                decrease = price - decrease_amount
        return max(decrease, 0)
    
    def __str__(self) -> str:
        return f"{self.amount}%"
    

class Product(models.Model):
    class Meta:
        verbose_name, verbose_name_plural = 'product', 'products'

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.FileField(upload_to='product/products', default='no_image.png', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='products')
    price = models.PositiveBigIntegerField()
    description = models.TextField()
    status = models.BooleanField(default=True)
    discount = models.ForeignKey(Discount, on_delete=models.CASCADE, related_name='products', default=None, null=True, blank=True)
    create_timestamp = models.DateField(auto_now_add=True)
    modify_timestamp = models.DateTimeField(auto_now=True)
    
    @property
    def final_price(self) -> int:
        result = self.price
        if self.discount is not None:
            result = self.discount.calculate_price(result)
            
        return result

    def __str__(self) -> str:
        return f"{self.title}-$({self.price})- ({self.discount}%)"
    

products/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from .models import Category, Brand, Discount, Product
from django.views.generic import ListView, DetailView, View
from django.shortcuts import get_object_or_404, get_list_or_404
from cart.forms import CartAddProductForm
from cart.cart import Cart
from .recommender import Recommender

# Create your views here.

class ProductListView(ListView):
    
    # def get(self, request, *args, **kwargs):
    #     products = Product.objects.all()
    #     products.order_by('-id')
    #     return render(request,'products/product_list.html',
    #                   {'products': products})

    context_object_name = "products"
    paginate_by = 12

    def get_queryset(self):
        result = Product.objects.all()
        kwargs = self.request.GET
        if "category" in kwargs:
            result = result.filter(category__slug=kwargs["category"])
        if "brand" in kwargs:
            result = result.filter(brand__slug=kwargs["brand"])
        return result
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


    
class ProductDetailView(DetailView):


  
    model = Product
    # context_object_name = "product"
    template_name = 'products/product_detail.html'
    
    def get(self, request, slug, *args, **kwargs):
        form = CartAddProductForm()
        product = get_object_or_404(Product,slug=slug)
        r = Recommender()
        recommended_products = r.suggest_products_for([product],4)
        return render(request, 'products/product_detail.html',
                        {'product':product,
                         'form':form,
                         'recommended_products':recommended_products})

    
    def post(self, request, slug, *args, **kwargs):
        product = get_object_or_404(Product, slug=slug)
        form = CartAddProductForm(request.POST)
        cart = Cart(request)

        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product, quantity=cd['quantity'])

            return redirect('cart:cart_detail')



class CategoryListView(ListView):
    
    # to override the default context 'object_list'
    context_object_name = 'parents'
    template_name = 'products/category_list.html'
    # to define the or retrive the custom queried data as context('parents')
    def get_queryset(self):
        parents =  Category.objects.filter(root=None)
        return parents

    # for additional context data to supply as context data
    def get_context_data(self, **kwargs: Any): 
        context = super().get_context_data(**kwargs)
        return context 

products/templates/products/category_list.html
{% extends 'base.html' %}

{% block title %}Category list{% endblock title %}

{% block content %}
    <h2><a href="{% url 'cart:cart_detail' %}">Your Cart</a></h2>
    <h1>The categories are:</h1>
    {% for parent in parents %}
        <h2>category name  - {{ parent.name }}</h2>
        
        <h1>The subcategories are:</h1>
        {% for child in parent.subcategories.all %}
            <h3>{{ child.name }}</h3>

        {% endfor %}

    {% endfor %}

{% endblock content %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ product.name }}{% endblock title %}


{% block content %}
    <h1>{{ product.title }}</h1>
    <h3>category - {{ product.category }}</h3>
    <h3>subcategory- {{ product.category.subcategories }}</h3>
    <h3>brand - {{ product.brand }}</h3>
    <h3>price - {{ product.price }}</h3>
    <h3>discount - {{ product.discount }}</h3>
    <h2>total - {{ product.final_price }}</h2>
    <form method="post" action="{% url 'cart:cart_add' product.id %}" >
        
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="add-to-cart">
    </form>

    {% if recommended_products %}
        <div class="recommendations">
            <h3>People who bought this also bought</h3>
            {% for p in recommended_products %}
                <div class="item">
                    <a href="{{ p.get_absolute_url }}">{{ p.title }}

                    </a>
                </div>
            {% endfor %}
        </div>
    {% endif %}


{% endblock content %}

products/templates/products/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}


{% block content %}
    <h2><a href="{% url 'cart:cart_detail' %}">Your Cart</a></h2>
    <h1><a href="{% url 'product:category_list' %}">View all categories</a> </h1>


    {% for product in products %}     
       <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>


        <h2><a href="{% url 'product:product_detail' product.slug %}">{{ product.title }}</a> </h2>
        <h3>category - {{ product.category }}</h3>
        <h3>brand - {{ product.brand }}</h3>
        <h3>price - {{ product.price }}</h3>
        <h3>discount - {{ product.discount }}</h3>
        <h2>total - {{ product.final_price }}</h2>

    {% endfor %}
{% endblock content %}